"""Shared UI helpers: badges, source cards, mode banner, friendly errors.

Badges return Markdown strings (so you can put them inside st.markdown text);
functions named show_* / *_card / *_banner draw directly with Streamlit.
"""

from __future__ import annotations

import streamlit as st

from mixup.llm import LLMError
from mixup.models import Citation, DocMeta

STATUS_INFO = {
    "in_force": ("In force", "green"),
    "superseded": ("Superseded", "red"),
    "record": ("Record", "blue"),
}
TYPE_LABELS = {
    "circular": "Circular / Pekeliling",
    "guideline": "Guideline / Garis Panduan",
    "sop": "SOP",
    "policy": "Policy / Dasar",
    "minutes": "Minutes / Minit",
    "report": "Report / Laporan",
    "other": "Document",
}
LANGUAGE_LABELS = {"ms": "BM", "en": "EN", "mixed": "BM + EN"}
CONFIDENCE_INFO = {
    "high": ("High confidence", "green"),
    "medium": ("Medium confidence", "orange"),
    "low": ("Low confidence", "gray"),
    "none": ("Not found in documents", "gray"),
}
FICTIONAL_NOTE = "All sample documents are FICTIONAL (Kerajaan Negeri Contoh) and for demo only."

# Session-state key prefixes owned by each tab (used by "Reset demo").
TAB_PREFIXES = ("ask_", "map_", "upload_", "minutes_", "library_")


def _badge(text: str, color: str) -> str:
    safe = text.replace("[", "(").replace("]", ")")
    return f":{color}-badge[{safe}]"


def status_badge(status: str) -> str:
    """Markdown badge for a document status, e.g. ':green-badge[In force]'."""
    label, color = STATUS_INFO.get(status, (status or "Unknown", "gray"))
    return _badge(label, color)


def confidence_badge(level: str) -> str:
    label, color = CONFIDENCE_INFO.get(level, (level or "Unknown", "gray"))
    return _badge(label, color)


def type_label(doc_type: str) -> str:
    return TYPE_LABELS.get(doc_type, doc_type or "Document")


def language_label(lang: str) -> str:
    return LANGUAGE_LABELS.get(lang, lang or "?")


def doc_caption(doc: DocMeta) -> str:
    """One line like 'Bil. 1/2024 - 2024-02-15 - Circular / Pekeliling - BM'."""
    parts = [doc.number or doc.doc_id, doc.date_issued, type_label(doc.doc_type), language_label(doc.language)]
    return " - ".join(p for p in parts if p)


def doc_heading(doc: DocMeta) -> str:
    """Markdown: bold title followed by its status badge."""
    return f"**{doc.title}** {status_badge(doc.status)}"


def source_card(citation: Citation) -> None:
    """Draw one source: [S1] title, number, page/section, snippet, status."""
    with st.container(border=True):
        st.markdown(f"**[{citation.label}]** {citation.title} {status_badge(citation.status)}")
        where = f"{citation.number or citation.doc_id} - section/page {citation.page_no}"
        if citation.heading:
            where += f" - {citation.heading}"
        st.caption(where)
        if citation.snippet:
            st.markdown(f"> {citation.snippet}")


def mode_banner(ctx) -> None:
    """Sidebar badge: Online (Claude on Amazon Bedrock) or Offline (keyword search)."""
    llm = ctx.llm
    if llm.online:
        st.markdown(_badge("Online", "green") + " Claude on Amazon Bedrock")
        st.caption(llm.label)
        if llm.last_error:
            st.caption(f"Last AI problem: {llm.last_error}")
    else:
        st.markdown(_badge("Offline", "orange") + " keyword search fallback")
        reason = getattr(llm, "reason", "") or llm.last_error or ""
        if reason:
            st.caption(reason)


def mode_caption(mode: str) -> None:
    """Small line under a result saying how it was produced."""
    if mode == "ai":
        st.caption("Generated by Claude on Amazon Bedrock from the documents above.")
    else:
        st.caption("Offline mode: produced by MixUp's built-in rules and keyword search (no AI call).")


def show_llm_error(err: LLMError | str | None) -> None:
    """Explain why the AI was not used, without scaring the audience."""
    if not err:
        return
    message = err.message if isinstance(err, LLMError) else str(err)
    st.info(f"AI not used: {message}", icon=":material/cloud_off:")


def clear_tab_state() -> None:
    """Forget every tab's session_state (used by Reset demo)."""
    for key in list(st.session_state.keys()):
        if str(key).startswith(TAB_PREFIXES):
            del st.session_state[key]
